# **Coding and Programming**

## ***Capítulo 6***

### ***Resolución de problemas con algoritmos***

- **Unidad 30.** Enfoque Greedy algoritmos voraces o ávidos.
- **Unidad 31.** Divide y vencerás
- **Unidad 32.** Programación dinámica
- **Unidad 33.** Backtracking


___

## ***Q 30-01***

Este es el problema del intercambio de monedas.

Tienes una moneda de 400 wones.

Escriba el resultado de cómo el algoritmo `coin_change()` determina el cambio de la moneda de 800 wones.
```
coins  = [500, 400, 100, 50, 10]
amount = int(input("Ingrese la cantidad: "))
changes= coin_change(coins, amount)
print(changes, len(changes))

Ingrese la cantidad: 800
```

In [21]:
# Funcion que realiza cambio de monedas
def coin_change (coins, amount):
    # Lista vacía para agregar solución 
    changes = [] 
    largest = 0 
    
    # Verificar las monedas necesarias para el cambio 
    # Y agregarlas a las lista vacía 
    while amount > 0:
        if coins [largest] <= amount: 
            changes.append(coins[largest])
            amount -=coins[largest]
        else: 
            largest +=1
    return changes

# Las monedas que pueden ser posibles soluciones 
coins = [500, 400, 100, 50, 10]
amount = int(input('Ingrese el valor que desee cambiar: '))
changes = coin_change(coins, amount)
print(f'El cambio de {amount} es: \n {changes}')

El cambio de 800 es: 
 [500, 100, 100, 100]


___

## ***Q 31-01***

Tienes 8 monedas idénticas numeradas del 1 al 8. De estas, solo una moneda es más pesada que la otra.

Suponiendo que puede pesar monedas con una balanza equilibrada, diseñe un algoritmo que encuentre la moneda más pesada.

En este momento, ¿cuántas veces se debe usar al menos la balanza?

In [18]:
# Función principal que llama a la función recursiva 'hevy_coin'
def heviest_coin(monedas):
    result, counter = hevy_coin(monedas, 0, len(monedas) - 1)
    return result + 1, counter

# Función recursiva para encontrar la moneda más pesada
def hevy_coin(coins, left, right, counter=0):
    if left == right:
        return left, counter

    # Si solo hay una moneda en el rango, esa es la más pesada
    middle = (left + right) // 2 

    # Comparar los pesos de los dos grupos resultantes de dividir las monedas en dos mitades
    if weigh(coins[left:middle], coins[middle:right+ +2]) > 0:
        # Si el grupo izquierdo es más pesado, llamar recursivamente a la función en el lado izquierdo
        result, count = hevy_coin(coins, left, middle - 1, counter +1)
    else:
        # Si el grupo derecho es más pesado o tienen el mismo peso, llamar recursivamente a la función en el lado derecho
        result, count = hevy_coin(coins, middle+1, right, counter +1)

    return result, count 

# Función que calcula la diferencia de peso entre dos grupos de monedas
def weigh(left_group, right_group):
    left_weight = sum(left_group)
    right_weight = sum(right_group)
    return left_weight - right_weight

# Definir una lista de monedas
monedas = [1, 2, 3, 4, 5, 6, 7, 8]  

# Encontrar la moneda más pesada
resultado, counter  = heviest_coin(monedas)

# Imprimir el resultado
print(f"La moneda más pesada es la número {resultado}")
print(f'Se encontro el resultado en {counter} iteraciones')


La moneda más pesada es la número 8
Se encontro el resultado en 3 iteraciones


___

## ***Q 31-02***

Hay nueve monedas idénticas numeradas del 1 al 9 en el problema anterior.

Diseñe un algoritmo para encontrar una moneda pesada en este caso.

En este momento, ¿cuántas veces se debe usar al menos la balanza?

In [17]:
# Función principal que llama a la función recursiva 'hevy_coin'
def heviest_coin(monedas):
    result, counter = hevy_coin(monedas, 0, len(monedas) - 1)
    return result + 1, counter

# Función recursiva que utiliza el enfoque de "divide y vencerás" para encontrar la moneda más pesada
def hevy_coin(coins, left, right, counter=0):
    if left == right:
        return left, counter

    # Si solo hay una moneda en el rango, esa es la más pesada
    middle = (left + right) // 2 

    # Comparar los pesos de los dos grupos resultantes de dividir las monedas en dos mitades
    if weigh(coins[left:middle], coins[middle:right+ +2]) > 0:
        # Si el grupo izquierdo es más pesado, llamar recursivamente a la función en el lado izquierdo
        result, count = hevy_coin(coins, left, middle - 1, counter +1)
    else:
        # Si el grupo derecho es más pesado o tienen el mismo peso, llamar recursivamente a la función en el lado derecho
        result, count = hevy_coin(coins, middle+1, right, counter +1)

    return result, count  # Añadir esta línea para devolver el resultado y el contador

# Función que calcula la diferencia de peso entre dos grupos de monedas
def weigh(left_group, right_group):
    left_weight = sum(left_group)
    right_weight = sum(right_group)
    return left_weight - right_weight

# Crear una lista de monedas
monedas = [1, 2, 3, 4, 5, 6, 7, 8, 9]  

# Encontrar la moneda más pesada
resultado, counter  = heviest_coin(monedas)

# Imprimir el resultado
print(f"La moneda más pesada es la número {resultado}")
print(f'Se encontro el resultado en {counter} iteraciones')

La moneda más pesada es la número 9
Se encontro el resultado en 3 iteraciones


___

## ***Q 32-01***

Analice el resultado de la ejecución del siguiente código y compárelo con el rendimiento de las funciones `fib1()`, `fib2()` y `fib3()`.
```
def fib4(n):
    if n <= 1:
        return n
    else:
        a,b = 0,1
        for i in range(2, n + 1):
            a,b = b,a+b
        return b

N = int(input("Ingrese un numero: "))
print(fib4(N))


Ingrese un numero:
```


In [16]:
def fib1(n):
    if n == 0 or n == 1:
        return n 
    else: 
        return fib1(n-1) + fib1(n-2)
    
N = int(input("Ingrese un numero: "))
print(fib1(N))

55


In [15]:
F = {0: 0, 1: 1}

def fib2(n):
    if n in F:
        return F[n]
    else: 
        F[n] = fib2(n-1)+ fib2(n-2)
        return F[n]
    
N = int(input("Ingrese un numero: "))
print(fib1(N))

55


In [14]:
def fib3(F, n):
    if n <=1:
        return F[n]
    else: 
        if F[n] < 0:
            F[n] = fib3(F, n-1)+ fib3(F, n-2)
        return F[n]
    
N = int(input("Ingrese un numero: "))
F = [0, 1] + [-1] * (N-1)
print(fib3(F, N))


55


In [13]:
def fib4(n):
    if n <= 1:
        return n
    else:
        a,b = 0,1
        for i in range(2, n + 1):
            a,b = b,a+b
        return b

N = int(input("Ingrese un numero: "))
print(fib4(N))

55


####  **Respuesta:**

- **`fib1():`** Es el mas lento e incrementa a medida que el numero aumenta.
  
- **`fib2() y fib3():`** Son más eficientes en comparacion a `fib1()` aunque puede llegar ser lento y consumir mucha memoria con valores más grandes.

- **`fib4():`** Es el más eficiente con respecto a rendimiento y memoria. 


___

## ***Q 32-02***

Analice el resultado de la ejecución del siguiente código y compárelo con el rendimiento de las funciones `bin1()` y `bin2()`.
```
def bin3(n,k):
    B = [0] * (n + 1)
    for i in range(n + 1):
        for j in range(n, -1, -1):
            if j==0 or j==i:
                B[j] = 1
            else:
                B[j] = B[j] B[j-1]
    return B[k]


for i in range(10):
    for j in range(i+1):
        print(bin3(i,j),end=" ")
    print()
```

In [9]:
def bin1(n, k):
    if k == 0 or n == k:
        return 1
    else:
        return bin1(n-1, k-1) + bin1(n -1, k)
    
n = int(input('Ingrese el valor de n: '))
k = int(input('Ingrese el valor de k: '))
print(f'Binomial({n}, {k}) es {bin1(n, k)}')

Binomial(5, 3) es 10


In [12]:
def bin2(n, k):
    B = [[0] * (i + 1) for i in range(n + 1)]

    for i in range (n + 1):
        for j in range(i + 1):
            if j == 0 or j == i:
                B[i][j] = 1
            else:
                B[i][j] = B[i - 1][j - 1]               
    return B[n][k]


n = int(input('Ingrese el valor de n: '))
k = int(input('Ingrese el valor de k: '))
print(f'Binomial({n}, {k}) es {bin1(n, k)}')

Binomial(5, 3) es 10


In [ ]:
def bin3(n, k):
    B = [0] * (n + 1)
    for i in range(n + 1):
        for j in range(n, -1, -1):
            if j == 0 or j == i:
                B[j] = 1
            else:
                B[j] = B[j] + B[j -1]
    return B[k]

for i in range(10):
    for j in range(i+1):
        print(bin3(i,j),end=" ")
    print()

####  **Respuesta:**

**`bin2()`** muestra ser la opción mas acertada y eficiente de las tres.

___

## ***Q 33-01***

### ***Resolver cuadrado mágico utilizando backtracking.***
#### ***Requisitos:***

- Los números a utilizar son del 0 - 8.
- No se puede repitir ningún número en la matriz. 
- La suma de las columnas, filas y diagonales debe ser igual 12.

In [22]:
import numpy as np

def is_valid(square):
    # Verificar si se cumple la condición de que la suma de filas, columnas y diagonales sea igual a 12
    return all(np.sum(square, axis=0) == 12) and all(np.sum(square, axis=1) == 12) and np.trace(square) == 12 and np.trace(np.fliplr(square)) == 12


def valid_number(square, fila, columna, num):
    # Verificar si el número no se repite en la fila
    return (
        num not in square[fila, :] and
        num not in square[:, columna] and
        num not in square[fila - fila % 3: fila - fila % 3 + 3, columna - columna % 3: columna - columna % 3 + 3]
    )
 

def solve_square(square, fila=0, columna=0):

    if fila == 3:
        # Si hemos llegado al final del cuadrado, verificar si es una solución
        if is_valid(square):
            print("Solución encontrada:")
            print(square)
            return True
        return False

    # Si el número ya está dado en la entrada, continuar con el siguiente
    if square[fila, columna] != 9:
        return solve_square(square, fila + (columna + 1) // 3, (columna + 1) % 3)

    # Probar números del 0 al 8
    for num in range(9):
        if valid_number(square, fila, columna, num):
            square[fila, columna] = num
            
            # Mover a la siguiente casilla
            if solve_square(square, fila + (columna + 1) // 3, (columna + 1) % 3):
                return True
            # Si no lleva a una solución, deshacer el cambio
            square[fila, columna] = 9

    # No se encontró ninguna solución para este estado
    return False


# Matriz 
square = np.array([
    [9, 9, 9],
    [9, 9, 8],
    [5, 6, 1],
])

# Llamar a la función de resolución
solve_square(square)

Solución encontrada:
[[7 2 3]
 [0 4 8]
 [5 6 1]]


True

___

# **Fin**