----------
# **Resolución de Problemas con Algoritmos**

-----------------------------------
----------------------------------
## **Backtracking**
---------------------------------
----------------------------------
El backtracking es una técnica de búsqueda exhaustiva que se utiliza para encontrar todas las soluciones factibles de un problema. 

En lugar de probar todas las posibilidades de manera indiscriminada, el backtracking avanza paso a paso y vuelve atrás ("backtrack") cuando se encuentra en una situación que no puede llevar a una solución válida.

------------------------------
### ***Pasos Clave:***
----------------------------

1. **Definición del Problema:**
   - Identifica el problema que deseas resolver y define las restricciones y objetivos del mismo.
  
2. **Estructura de Datos:**
   - Utiliza una estructura de datos para representar el estado actual de la solución. Esto podría ser un conjunto, una lista, una matriz u otra estructura según el problema.
  
3. **Elección de Decisión:**
   - Realiza una elección en el estado actual. Esto puede ser colocar una pieza en un tablero, seleccionar un camino en un grafo, etc.
  
4. **Validación:**
   - Verifica si la elección tomada en el paso anterior cumple con las restricciones del problema y si es una solución válida.

5. **Avance Recursivo:**
   - Si la elección es válida, avanza al siguiente estado recursivamente y repite los pasos 3-4. Si llegas a un estado donde no puedes avanzar más, retrocedes ("backtrack").
  
6. **Restauración del Estado:**
   - Cuando retrocedes, restaura el estado anterior para deshacer la elección que no condujo a una solución válida.
  
7. **Verificación de Todas las Soluciones:**
   - Repite el proceso hasta que hayas explorado todas las posibles combinaciones o hasta que encuentres la cantidad deseada de soluciones

-----------------------
### ***Ejemplo Práctico: Resolver un Sudoku***
-----------------------------

In [2]:
# Esta función toma una cuadrícula 2D como entrada y la imprime en un formato de sudoku
def print_sudoku(grid):
    for row in grid:
        # El método join() combina todos los elementos de un iterable (en este caso, row) 
        # en una cadena, con el delimitador especificado (en este caso, un espacio).
        print(" ".join(map(str, row)))
        
# Esta función verifica si un número dado se puede colocar en la posición dada en la cuadrícula
def is_valid_move(grid, row, col, num):
    # Verificar si el número ya existe en la fila o la columna actuales
    for i in range(9):
        if grid[row][i] == num or grid[i][col] == num:
            return False
        
    # Verificar si el número existe en el bloque 3x3 actual
    start_row, start_col = 3 * (row // 3), 3 * (col // 3)
    for i in range(3):
        for j in range(3):
            if grid[start_row + i][start_col + j] == num:
                return False
            
    # Si el número no existe en la fila, columna o bloque, se puede mover
    return True

# Esta función resuelve la cuadrícula de sudoku dada utilizando recursión y backtracking
def solve_sudoku(grid):
    # Iterar a través de cada celda de la cuadrícula
    for row in range(9):
        for col in range(9):
            # Si la celda está vacía, intentar colocar cada número de 1 a 9 en ella
            if grid[row][col] == 0: 
                for num in range(1, 10):
                    # Verificar si el número se puede colocar en la posición actual
                    if is_valid_move(grid, row, col, num):
                        grid[row][col] = num
                        # Si se puede resolver la cuadrícula con el número actual, devolver True
                        if solve_sudoku(grid):  
                            return True
                        # Si la cuadrícula no se puede resolver, restablecer la celda a 0 y probar el siguiente número
                        grid[row][col] = 0  
                # Si ningún número se puede colocar en la celda actual, devolver False
                return False  
            
    # Si todas las celdas se han llenado, la cuadrícula está resuelta
    return True  

# Definir una cuadrícula de sudoku de ejemplo
grid1 = [
    [3, 0, 6, 5, 0, 8, 4, 0, 0],
    [5, 2, 0, 0, 0, 0, 0, 0, 0],
    [0, 8, 7, 0, 0, 0, 0, 3, 1],
    [0, 0, 3, 0, 1, 0, 0, 8, 0],
    [9, 0, 0, 8, 6, 3, 0, 0, 5],
    [0, 5, 0, 0, 9, 0, 6, 0, 0],
    [1, 3, 0, 0, 0, 0, 2, 5, 0],
    [0, 0, 0, 0, 0, 0, 0, 7, 4],
    [0, 0, 5, 2, 0, 6, 3, 0, 0]
]

# Imprimir la cuadrícula de sudoku original
print("Sudoku original:")
print_sudoku(grid1)

# Resolver la cuadrícula de sudoku
if solve_sudoku(grid1):
    # Imprimir la cuadrícula de sudoku resuelta
    print("\nSolución:")
    print_sudoku(grid1)

# Si no se pudo resolver cuadribula de sudoku
else:
    # Imprimir No hay Solución 
    print("\nNo hay solución.")


Sudoku original:
3 0 6 5 0 8 4 0 0
5 2 0 0 0 0 0 0 0
0 8 7 0 0 0 0 3 1
0 0 3 0 1 0 0 8 0
9 0 0 8 6 3 0 0 5
0 5 0 0 9 0 6 0 0
1 3 0 0 0 0 2 5 0
0 0 0 0 0 0 0 7 4
0 0 5 2 0 6 3 0 0

Solución:
3 1 6 5 7 8 4 9 2
5 2 9 1 3 4 7 6 8
4 8 7 6 2 9 5 3 1
2 6 3 4 1 5 9 8 7
9 7 4 8 6 3 1 2 5
8 5 1 7 9 2 6 4 3
1 3 8 9 4 7 2 5 6
6 9 2 3 5 1 8 7 4
7 4 5 2 8 6 3 1 9


-------------------------------------------
### ***Ejemplo Práctico: Cuadrado Mágico***
-------------------------------------------
#### ***Requisitos:***

- Los números a utilizar son del 0 - 8.
- No se puede repitir ningún número en la matriz. 
- La suma de las columnas, filas y diagonales debe ser igual 12.

In [4]:
# Importar la librería numpy para trabajar con matrices de una manera más sencilla
import numpy as np

# Función que verifica que la suma de los diagonales, filas y columnas sea 12
def is_valid(square):
    return all(np.sum(square, axis=0) == 12) and all(np.sum(square, axis=1) == 12) and np.trace(square) == 12 and np.trace(np.fliplr(square)) == 12

# Función que verifica si un número es válido en una posición específica del cuadrado
def valid_number(square, fila, columna, num):
    return (
        num not in square[fila, :] and
        num not in square[:, columna] and
        num not in square[fila - fila % 3: fila - fila % 3 + 3, columna - columna % 3: columna - columna % 3 + 3]
    )
 
# Función recursiva para resolver el cuadrado mágico
def solve_square(square, fila=0, columna=0):

    # Verificar si hemos llegado al final del cuadrado
    if fila == 3:
        # Si es un cuadrado mágico, imprimir la solución y retornar True
        if is_valid(square):
            print("Solución encontrada:")
            print(square)
            return True
        # Si no es un cuadrado mágico, retornar False
        return False

    # Verificar si la celda actual ya contiene un número (diferente de 9)
    if square[fila, columna] != 9:
        # Mover a la siguiente celda
        return solve_square(square, fila + (columna + 1) // 3, (columna + 1) % 3)

    # Intentar asignar números del 0 al 8 en la celda actual
    for num in range(9):
        if valid_number(square, fila, columna, num):
            # Asignar el número si es válido
            square[fila, columna] = num
            # Llamada recursiva para seguir resolviendo
            if solve_square(square, fila + (columna + 1) // 3, (columna + 1) % 3):
                return True
            # Si no lleva a una solución, deshacer el cambio
            square[fila, columna] = 9
            
    # Si no se encuentra ninguna solución para la celda actual, retornar False
    return False

# Ejemplo de un cuadrado mágico parcialmente lleno (9 representa celdas vacías)
square = np.array([
    [9, 9, 9],
    [9, 9, 8],
    [5, 6, 1],
])

# Llamar a la función para resolver el cuadrado mágico
solve_square(square)

Solución encontrada:
[[7 2 3]
 [0 4 8]
 [5 6 1]]


True